name: humblenet-linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 

    - name: Install clang++ and deps
      run: |
        sudo apt update
        sudo apt install -y clang libpcap-dev libcap2-dev       

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build websockets
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target websockets-build

    - name: Build peer-server
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target peer-server

    - name: Build ALL
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Build humblenet_asmjs_amalgamation
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target humblenet_asmjs_amalgamation

    - name: Upload humblenet bundle
      uses: actions/upload-artifact@v4
      with:
        name: humblenet
        path: |
          build/peer-server.bin.x86_64
          build/humblenet_asmjs_amalgam.cpp
          src/humblenet/include/*
